// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaTsofxg3-NJrrCOE6CAjfcLGV-l47xu0',
    appId: '1:478756589985:web:0dd6a431d32499e2647be0',
    messagingSenderId: '478756589985',
    projectId: 'cards-app-dev-426b3',
    authDomain: 'cards-app-dev-426b3.firebaseapp.com',
    storageBucket: 'cards-app-dev-426b3.firebasestorage.app',
    measurementId: 'G-G1302ZRE6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_1qiRW0HaylRYoe2LLrNPwiBAT8TYFw',
    appId: '1:478756589985:android:f4e37680b3404aaf647be0',
    messagingSenderId: '478756589985',
    projectId: 'cards-app-dev-426b3',
    storageBucket: 'cards-app-dev-426b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4OefGJU6sU4-cMoqYKPtmggeguml9J3U',
    appId: '1:478756589985:ios:4ef4338013ea167e647be0',
    messagingSenderId: '478756589985',
    projectId: 'cards-app-dev-426b3',
    storageBucket: 'cards-app-dev-426b3.firebasestorage.app',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4OefGJU6sU4-cMoqYKPtmggeguml9J3U',
    appId: '1:478756589985:ios:4ef4338013ea167e647be0',
    messagingSenderId: '478756589985',
    projectId: 'cards-app-dev-426b3',
    storageBucket: 'cards-app-dev-426b3.firebasestorage.app',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaTsofxg3-NJrrCOE6CAjfcLGV-l47xu0',
    appId: '1:478756589985:web:3d89c71651268cc9647be0',
    messagingSenderId: '478756589985',
    projectId: 'cards-app-dev-426b3',
    authDomain: 'cards-app-dev-426b3.firebaseapp.com',
    storageBucket: 'cards-app-dev-426b3.firebasestorage.app',
    measurementId: 'G-ZWC2X8K8RM',
  );
}
