// =============== IMPORTS ===============
// Bring in Flutter's UI toolkit: widgets like Text, Button, Scaffold, etc.
import 'package:flutter/material.dart';
// Core Firebase package. Needed before using any Firebase services.
import 'package:firebase_core/firebase_core.dart';
// Firebase Authentication: sign up, sign in, sign out, current user.
import 'package:firebase_auth/firebase_auth.dart';
// Cloud Firestore: NoSQL database where we store users, matches, etc.
import 'package:cloud_firestore/cloud_firestore.dart';
// Auto-generated by `flutterfire configure`. Holds your Firebase project config.
import 'firebase_options.dart';

// ------------------- MAIN FUNCTION -------------------
// Entry point of the Flutter app. Must be async because we await Firebase init.
Future<void> main() async {
  // Make sure Flutter engine is fully ready before we do async work.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase for this app using the options from firebase_options.dart.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Launch the app by creating a MyApp widget and attaching it to the screen.
  runApp(const MyApp());
}

// ------------------- MAIN APP WIDGET -------------------
// MyApp is the top-level widget. In Flutter, everything is a widget.
class MyApp extends StatelessWidget {
  // const constructor: no internal state to change.
  const MyApp({super.key});

  // build() returns the UI for this widget.
  @override
  Widget build(BuildContext context) {
    // MaterialApp sets up global app settings: title, theme, first screen.
    return MaterialApp(
      debugShowCheckedModeBanner: false,                  // Hide "debug" ribbon.
      title: 'Card Games Compendium',                     // App name.
      theme: ThemeData(
        useMaterial3: true,                               // Use Material Design 3.
        colorSchemeSeed: Colors.indigo,                   // Seed color for theming.
      ),
      home: const AuthGate(),                             // First screen shown.
    );
  }
}

// ------------------- AUTH GATE -------------------
// This widget decides which screen to show based on login state.
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    // StreamBuilder listens to a stream (continuous events over time).
    // Here we listen to FirebaseAuth for changes in the current user.
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),   // Emits User? when login state changes.
      builder: (context, snap) {
        // While Firebase is figuring things out, show a loading spinner.
        if (snap.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // snap.data is the current user. If null, nobody is logged in.
        final user = snap.data;

        // If no user, show the AuthScreen (login/register form).
        if (user == null) {
          return AuthScreen();
        }

        // If we have a user, show the HomeScreen.
        return HomeScreen();
      },
    );
  }
}

// ------------------- AUTH SCREEN (LOGIN / REGISTER) -------------------
// This one screen handles both registering a new user and logging in.
class AuthScreen extends StatefulWidget {
  AuthScreen({super.key});

  @override
  State<AuthScreen> createState() => _AuthScreenState(); // Creates the mutable State object.
}

// Stateful widget = the screen can change (e.g., toggling between login/register).
class _AuthScreenState extends State<AuthScreen> {
  // GlobalKey lets us validate the entire <Form>.
  final _formKey = GlobalKey<FormState>();

  // Controllers read and modify text inside TextFormField widgets.
  final _emailC = TextEditingController();                // Holds email input.
  final _passwordC = TextEditingController();             // Holds password input.
  final _usernameC = TextEditingController();             // Holds username input (register only).

  // Simple flags for UI state.
  bool _isLogin = true;                                   // true: login mode, false: register mode.
  bool _busy = false;                                     // true when waiting for Firebase (disables buttons).
  String? _error;                                         // Error text to show under the form.

  // --- Helper function: check if a username is available in Firestore ---
  Future<bool> _usernameAvailable(String username) async {
    final unameLower = username.trim().toLowerCase();     // Normalize (remove spaces + lowercase).
    if (unameLower.length < 3) return false;              // Too short? Not allowed.

    // Point to /usernames/{usernameLower} document.
    final doc = await FirebaseFirestore.instance
        .collection('usernames')
        .doc(unameLower)
        .get();

    // If the doc exists, name is taken. If not, it's available.
    return !doc.exists;
  }

  // --- Main handler when the big button is pressed (Login or Register) ---
  Future<void> _submit() async {
    // First, run all validators in the Form. If any fail, stop.
    if (!_formKey.currentState!.validate()) return;

    // Set "busy" (disables button) and clear previous error.
    setState(() {
      _busy = true;
      _error = null;
    });

    try {
      // ========== LOGIN PATH ==========
      if (_isLogin) {
        // Ask Firebase Auth to sign in with email+password.
        await FirebaseAuth.instance.signInWithEmailAndPassword(
          email: _emailC.text.trim(),
          password: _passwordC.text.trim(),
        );
        return;                                           // AuthGate will notice and push Home.
      }

      // ========== REGISTER PATH ==========
      final username = _usernameC.text.trim();            // Read username from the field.
      final unameLower = username.toLowerCase();          // Lowercase version for consistent uniqueness.

      // Step 1: Quick availability check so we can show a friendly message early.
      final ok = await _usernameAvailable(username);
      if (!ok) {
        setState(() => _error = 'That username is already taken.');
        return;                                           // Stop registration here.
      }

      // Step 2: Create the actual Firebase Auth user account.
      final cred = await FirebaseAuth.instance.createUserWithEmailAndPassword(
        email: _emailC.text.trim(),
        password: _passwordC.text.trim(),
      );
      final uid = cred.user!.uid;                         // Unique id assigned by Firebase Auth.

      // References to the collections we will write to.
      final users = FirebaseFirestore.instance.collection('users');       // /users
      final usernames = FirebaseFirestore.instance.collection('usernames'); // /usernames

      // Step 3: Transaction = all-or-nothing write to reserve username and create profile.
      await FirebaseFirestore.instance.runTransaction((tx) async {
        final unameRef = usernames.doc(unameLower);       // /usernames/{usernameLower}
        final unameSnap = await tx.get(unameRef);         // Read inside the transaction.

        // If somebody else claimed it milliseconds before us, abort.
        if (unameSnap.exists) {
          throw StateError('USERNAME_TAKEN_RACE');        // We'll catch this below.
        }

        // Reserve the username so nobody else can take it later.
        tx.set(unameRef, {
          'uid': uid,                                     // Who owns this username.
          'username': username,                           // Pretty/original-casing copy.
          'createdAt': FieldValue.serverTimestamp(),      // Server time for auditing.
        });

        // Create the user's public profile document.
        tx.set(users.doc(uid), {
          'username': username,                           // Display name.
          'usernameLower': unameLower,                    // For case-insensitive lookups.
          'email': _emailC.text.trim(),                   // Copy of email (optional).
          'photoUrl': null,                               // Placeholder for future avatar.
          'createdAt': FieldValue.serverTimestamp(),      // Joined date.
        });
      });
    } on FirebaseAuthException catch (e) {
      // Typical auth errors: invalid-email, weak-password, email-already-in-use, etc.
      setState(() => _error = e.message);
    } on StateError catch (e) {
      // Race condition: username taken in-between our check and our write.
      if (e.message == 'USERNAME_TAKEN_RACE') {
        try {
          // Clean up the newly-created Auth user because we couldn't reserve the name.
          await FirebaseAuth.instance.currentUser?.delete();
        } catch (_) {
          // Ignore failure (user may need re-auth to delete). Not critical for your flow.
        }
        setState(() => _error = 'That username was just taken. Please choose another.');
      } else {
        setState(() => _error = 'Something went wrong. Please try again.');
      }
    } catch (e) {
      // Anything else unexpected (network issues, etc.).
      setState(() => _error = 'Unexpected error: $e');
    } finally {
      // Whatever happens, turn off "busy" so the button is clickable again.
      if (mounted) setState(() => _busy = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    // Build the visual layout of the auth screen.
    return Scaffold(
      appBar: AppBar(title: Text(_isLogin ? 'Login' : 'Create account')), // Title changes by mode.
      body: Padding(
        padding: const EdgeInsets.all(16),                 // Space around the form.
        child: Form(
          key: _formKey,                                   // Hook validators to this form.
          child: ListView(                                 // Scrollable column.
            children: [
              // Username field appears only when registering.
              if (!_isLogin)
                TextFormField(
                  controller: _usernameC,                  // Read/write from _usernameC controller.
                  decoration: const InputDecoration(labelText: 'Username'),
                  textInputAction: TextInputAction.next,   // Keyboard "next" moves to next field.
                  validator: (v) =>                        // Validate input.
                  (v == null || v.trim().length < 3) ? 'Min 3 chars' : null,
                ),
              // Email field (always shown).
              TextFormField(
                controller: _emailC,
                decoration: const InputDecoration(labelText: 'Email'),
                keyboardType: TextInputType.emailAddress,  // Mobile keyboard shows @, etc.
                textInputAction: TextInputAction.next,
                validator: (v) =>
                (v == null || !v.contains('@')) ? 'Enter a valid email' : null,
              ),
              // Password field (always shown).
              TextFormField(
                controller: _passwordC,
                decoration: const InputDecoration(labelText: 'Password'),
                obscureText: true,                          // Hide text as dots.
                validator: (v) =>
                (v == null || v.length < 6) ? 'Min 6 chars' : null,
              ),
              const SizedBox(height: 16),                   // Spacing.

              // Error text (only shows if _error is not null).
              if (_error != null)
                Text(_error!, style: const TextStyle(color: Colors.red)),

              const SizedBox(height: 8),                    // Spacing.

              // Big action button. Disabled while _busy is true.
              FilledButton(
                onPressed: _busy ? null : _submit,
                child: Text(_isLogin ? 'Login' : 'Register'),
              ),

              // Small text button to switch between Login and Register modes.
              TextButton(
                onPressed: _busy ? null : () => setState(() => _isLogin = !_isLogin),
                child: Text(_isLogin
                    ? 'Need an account? Register'
                    : 'Have an account? Login'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ------------------- HOME SCREEN -------------------
// After login, this is the landing page. For now: Profile, Sign out, Add Test Match.
class HomeScreen extends StatelessWidget {
  HomeScreen({super.key});

  // Helper function: write a dummy match to Firestore under the current user.
  Future<void> _addTestMatch() async {
    final uid = FirebaseAuth.instance.currentUser!.uid;   // Current user's id.
    final matches = FirebaseFirestore.instance
        .collection('users')                               // Go to /users
        .doc(uid)                                          // Pick current user document
        .collection('matches');                            // Go to /users/{uid}/matches

    // Add one simple "match" document with game, result, and timestamp.
    await matches.add({
      'gameType': 'Blackjack',                             // Hardcoded example.
      'result': 'Win',                                     // Hardcoded example.
      'playedAt': FieldValue.serverTimestamp(),            // Server time for sorting.
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),                         // Screen title.
        actions: [
          // Button: go to Profile page.
          IconButton(
            tooltip: 'Profile',
            icon: const Icon(Icons.person),
            onPressed: () {
              Navigator.of(context).push(                   // Push a new page on top.
                MaterialPageRoute(builder: (_) => ProfileScreen()),
              );
            },
          ),
          // Button: sign out from Firebase Auth.
          IconButton(
            tooltip: 'Sign out',
            icon: const Icon(Icons.logout),
            onPressed: () => FirebaseAuth.instance.signOut(),
          ),
        ],
      ),
      // Body: simple center with one button to create a test match.
      body: Center(
        child: FilledButton.icon(
          icon: const Icon(Icons.add),                     // Leading plus icon.
          label: const Text('Add Test Match'),             // Button text.
          onPressed: _addTestMatch,                        // Call helper to write a doc.
        ),
      ),
    );
  }
}

// ------------------- MATCHES SCREEN -------------------
// Shows ALL matches for the current user (latest first). Uses a stream for live updates.
class MatchesScreen extends StatelessWidget {
  MatchesScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final uid = FirebaseAuth.instance.currentUser!.uid;   // Current user id.

    // Build a Firestore query: /users/{uid}/matches ordered by playedAt descending.
    final query = FirebaseFirestore.instance
        .collection('users')
        .doc(uid)
        .collection('matches')
        .orderBy('playedAt', descending: true);

    return Scaffold(
      appBar: AppBar(title: const Text('My Matches')),     // Screen title.
      body: StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
        stream: query.snapshots(),                         // Live listener for this query.
        builder: (context, snap) {
          // Show a spinner until the first batch of data arrives.
          if (snap.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          // If there is no data (or list is empty), show friendly message.
          if (!snap.hasData || snap.data!.docs.isEmpty) {
            return const Center(child: Text('No matches yet.'));
          }

          // Grab the list of documents (each is one match).
          final docs = snap.data!.docs;

          // Build a vertically scrollable list with dividers between items.
          return ListView.separated(
            itemCount: docs.length,                         // Number of matches.
            separatorBuilder: (_, __) => const Divider(height: 1), // Thin line between tiles.
            itemBuilder: (context, i) {
              final data = docs[i].data();                  // Map<String, dynamic> for this match.
              final gameType = (data['gameType'] ?? '-') as String;
              final result = (data['result'] ?? '-') as String;
              final ts = data['playedAt'];                  // May be a Timestamp or null.
              // Convert timestamp to DateTime (fallback to epoch if missing).
              final played = ts is Timestamp
                  ? ts.toDate()
                  : DateTime.fromMillisecondsSinceEpoch(0);

              // One row in the list.
              return ListTile(
                leading: const Icon(Icons.sports_esports),  // Gamepad icon.
                title: Text('$gameType • $result'),         // "Blackjack • Win"
                subtitle: Text(played.toLocal().toString()),// Date/time string.
              );
            },
          );
        },
      ),
    );
  }
}

// ------------------- PROFILE SCREEN -------------------
// Clean header card with username/email/join date, plus a "Recent Matches" list and "See all".
class ProfileScreen extends StatelessWidget {
  ProfileScreen({super.key});

  // Helper: turn a Firestore Timestamp into a short human string (YYYY-MM-DD HH:MM:SS).
  String _fmtDate(dynamic ts) {
    if (ts is! Timestamp) return '-';                      // If null or wrong type, show "-".
    final d = ts.toDate().toLocal();                       // Convert to local DateTime.
    final iso = d.toString();                              // "2025-11-06 12:34:56.789"
    return iso.split('.').first;                           // Drop milliseconds.
  }

  @override
  Widget build(BuildContext context) {
    final uid = FirebaseAuth.instance.currentUser!.uid;    // Current user id.

    // Reference to the user's profile document: /users/{uid}
    final userDoc = FirebaseFirestore.instance.collection('users').doc(uid);

    // Query last 5 matches for the "Recent Matches" box.
    final recentMatchesQuery = userDoc
        .collection('matches')
        .orderBy('playedAt', descending: true)
        .limit(5);

    return Scaffold(
      appBar: AppBar(title: const Text('Your Profile')),   // Title on top bar.
      body: StreamBuilder<DocumentSnapshot<Map<String, dynamic>>>(
        stream: userDoc.snapshots(),                       // Live read of /users/{uid}.
        builder: (context, userSnap) {
          // Show spinner while loading the profile.
          if (userSnap.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          // If profile doc missing, show message.
          if (!userSnap.hasData || !userSnap.data!.exists) {
            return const Center(child: Text('Profile not found'));
          }

          // Extract fields from the profile document.
          final data = userSnap.data!.data()!;
          final username = (data['username'] ?? '') as String;
          final email = (data['email'] ?? '') as String;
          final created = data['createdAt'];

          // Use a ListView so screen can scroll if content grows.
          return ListView(
            padding: const EdgeInsets.all(16),              // Outer padding.
            children: [
              // ===== Profile Header Card =====
              Card(
                elevation: 0,                                // Flat card (no drop shadow).
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),   // Rounded corners.
                  side: BorderSide(
                    color: Theme.of(context).colorScheme.outlineVariant, // Subtle border.
                  ),
                ),
                child: Padding(
                  padding: const EdgeInsets.all(16),         // Inner padding inside the card.
                  child: Row(
                    children: [
                      // Round avatar with the first letter of the username.
                      CircleAvatar(
                        radius: 36,
                        child: Text(
                          username.isEmpty ? 'U' : username[0].toUpperCase(),
                          style: const TextStyle(
                            fontSize: 24,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                      const SizedBox(width: 16),             // Space between avatar and text.
                      // Right side: username, email, join date.
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              username,
                              style: const TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                            const SizedBox(height: 4),
                            Text(
                              email,
                              style: TextStyle(
                                color: Theme.of(context)
                                    .colorScheme
                                    .onSurfaceVariant,     // Softer color for secondary text.
                              ),
                            ),
                            const SizedBox(height: 8),
                            Text(
                              'Joined: ${_fmtDate(created)}', // e.g., "Joined: 2025-11-06 12:34:56"
                              style: TextStyle(
                                fontSize: 12,
                                color: Theme.of(context)
                                    .colorScheme
                                    .onSurfaceVariant,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              const SizedBox(height: 16),                   // Space before the next section.

              // ===== "Recent Matches" header + See all button =====
              Row(
                children: [
                  const Expanded(
                    child: Text(
                      'Recent Matches',
                      style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
                    ),
                  ),
                  TextButton.icon(
                    onPressed: () {
                      // Navigate to the full history page.
                      Navigator.of(context).push(
                        MaterialPageRoute(builder: (_) => MatchesScreen()),
                      );
                    },
                    icon: const Icon(Icons.history),
                    label: const Text('See all'),
                  ),
                ],
              ),

              // ===== Recent Matches list (live, up to 5) =====
              StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
                stream: recentMatchesQuery.snapshots(),      // Listen to last 5 matches.
                builder: (context, matchSnap) {
                  // Show spinner while first set loads.
                  if (matchSnap.connectionState == ConnectionState.waiting) {
                    return const Center(
                      child: Padding(
                        padding: EdgeInsets.symmetric(vertical: 24),
                        child: CircularProgressIndicator(),
                      ),
                    );
                  }

                  // Get docs or empty list.
                  final docs = matchSnap.data?.docs ?? [];
                  // If no matches yet, show a friendly hint.
                  if (docs.isEmpty) {
                    return Padding(
                      padding: const EdgeInsets.symmetric(vertical: 12),
                      child: Text(
                        'No matches yet. Play a game from the Home screen.',
                        style: TextStyle(
                          color: Theme.of(context).colorScheme.onSurfaceVariant,
                        ),
                      ),
                    );
                  }

                  // Card containing a small list (non-scrollable because parent scrolls).
                  return Card(
                    elevation: 0,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                      side: BorderSide(
                        color: Theme.of(context).colorScheme.outlineVariant,
                      ),
                    ),
                    child: ListView.separated(
                      shrinkWrap: true,                      // Take only needed height.
                      physics: const NeverScrollableScrollPhysics(), // Don't scroll here.
                      itemCount: docs.length,
                      separatorBuilder: (_, __) => const Divider(height: 1),
                      itemBuilder: (context, i) {
                        final m = docs[i].data();            // One match record.
                        final game = (m['gameType'] ?? '-') as String;
                        final result = (m['result'] ?? '-') as String;
                        final played = _fmtDate(m['playedAt']); // Format date nicely.

                        return ListTile(
                          leading: const Icon(Icons.sports_esports), // Game icon.
                          title: Text(game),                         // Game name.
                          subtitle: Text(played),                    // When it happened.
                          trailing: Text(                            // Result on the right.
                            result,
                            style: TextStyle(
                              fontWeight: FontWeight.w600,
                              color: result.toLowerCase() == 'win'
                                  ? Colors.green                  // Green = win.
                                  : (result.toLowerCase() == 'loss'
                                  ? Colors.red               // Red = loss.
                                  : Theme.of(context).colorScheme.primary), // Other = neutral.
                            ),
                          ),
                        );
                      },
                    ),
                  );
                },
              ),
            ],
          );
        },
      ),
    );
  }
}